version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npx playwright install  # Command to download browser binaries
      - run:
          name: Run Playwright Tests
          command: npx playwright test

workflows:
  version: 2
  sample:
    jobs:
      - test
